/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/common/AppButton.vue')['default']
    AppContent: typeof import('./components/layout/AppContent.vue')['default']
    AppDialog: typeof import('./components/common/AppDialog.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppIcon: typeof import('./components/common/AppIcon.vue')['default']
    AppRightPanel: typeof import('./components/layout/AppRightPanel.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    AppStatusBar: typeof import('./components/layout/AppStatusBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
